name: qr_mobile_vision
description: "Plugin for reading QR codes using Firebase's Mobile Vision API."
version: 1.0.1+1
homepage: https://github.com/rmtmckenzie/flutter_qr_mobile_vision

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.github.rmtmckenzie.qrmobilevision
        pluginClass: QrMobileVisionPlugin
      ios:
        pluginClass: QrMobileVisionPlugin

dependencies:
  flutter:
    sdk: flutter
  native_device_orientation:
    git:
      url: https://github.com/fareesh/flutter_native_device_orientation.git
      ref: 412033ac0b5063ff88865885bf1a130186e496dc
